
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 15 10:19:09 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 27;
  public static final int SEMI = 35;
  public static final int LPAREN = 28;
  public static final int REPEAT = 7;
  public static final int INT = 32;
  public static final int FOR = 34;
  public static final int MINUS = 25;
  public static final int RCOR = 37;
  public static final int WRITE = 10;
  public static final int RPAREN = 29;
  public static final int AND = 22;
  public static final int LT = 17;
  public static final int OR = 23;
  public static final int RT = 18;
  public static final int BEGIN = 5;
  public static final int UNTIL = 8;
  public static final int NUM = 13;
  public static final int PLUS = 24;
  public static final int ASSIGN = 15;
  public static final int IF = 2;
  public static final int ID = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RETURN = 11;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int DIF = 21;
  public static final int VOID = 33;
  public static final int EQ = 16;
  public static final int REAL = 14;
  public static final int TIMES = 26;
  public static final int ELSE = 4;
  public static final int READ = 9;
  public static final int LCOR = 36;
  public static final int THEN = 3;
  public static final int END = 6;
  public static final int MENEQ = 19;
  public static final int MAYEQ = 20;
}

